# Generated by Django 4.1.5 on 2023-01-18 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["nom"],
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Toutes les utilisateurs",
            },
        ),
    ]
