# Generated by Django 4.1.5 on 2023-01-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_alter_review_options"),
        ("tickets", "0002_initial"),
        ("users", "0003_alter_user_managers_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="following", to="users.user"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="reviews_created",
            field=models.ManyToManyField(
                blank=True, related_name="reviews_created", to="reviews.review"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tickets_created",
            field=models.ManyToManyField(
                blank=True, related_name="tickets_created", to="tickets.ticket"
            ),
        ),
    ]
