# Generated by Django 4.1.5 on 2023-01-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, max_length=2048)),
                ("time_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tous les tickets",
                "ordering": ["user"],
            },
        ),
    ]
